mongo:
  image: mongo:3.2.0
  restart: always

backend:
  image: mavarazy/thanks-backend:latest
  restart: always
  ports:
    - "9000:9000"
  environment:
    - APPLICATION_SECRET=T1[a`5pd?fI<E<;<QG<rUg@ZS8o6`KjuJME6Pd/[MN3nz:aBMW8v:a0lKT`Zk;bD
  links:
    - mongo