version: 2
jobs:
  build:
    working_directory: ~/backend
    docker:
      - image: codestar/circleci-scala-sbt-git:scala-2.12.6-sbt-1.1.1
      - image: mongo:3.4.9
    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - restore_cache:
          keys:
            - backend-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
            - backend

      - run:
          command:
            sbt compile test:compile exit

      - save_cache:
          key: backend-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
          paths:
            - target/resolution-cache
            - target/streams
            - project/target/resolution-cache
            - project/target/streams
            - ~/.sbt
            - ~/.iv2/cache
            - ~/.m2

      - save_cache:
          # Changing this to a different key is the only way to remove old dependencies from the cache and/or generate a more up-to-date cache
          key: backend
          paths:
            - ~/.sbt
            - ~/.iv2/cache
            - ~/.m2

      - run:
          command:
            sbt clean coverage test

      - store_test_results:
          path: target/test-reports

      - run:
          name: Update Coveralls
          command:
            sbt coverageReport coveralls

      - run:
          name: Add docker
          command:
            apk add --no-cache docker

      - run:
          name: Create local docker image
          command:
            sbt docker:publishLocal

      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS


      - run:
          name: Publish Docker image
          command: docker push loveit/backend

      - run:
          name: Update Sentry Release
          command: >
            curl https://sentry.io/api/hooks/release/builtin/200194/beb76b4a2cfa2e29c4231a284f2b4f5dd573c242a2a4223b7ba1f0226a8e838d/
            -X POST
            -H 'Content-Type: application/json'
            -d '{"version": "'$CIRCLE_BUILD_NUM'"}'
